# Generated by Buildr 1.3.4, change to your liking
# Standard maven2 repository
repositories.remote << 'http://www.ibiblio.org/maven2'

desc 'jsoncss-java'
define 'jsoncss-java' do
  project.group = 'com.github.skeletonzkay.css'
  project.version = '0.1-SNAPSHOT'
  compile.with 'org.json:json:jar:20090211'
  package :jar, :id => 'jsoncss-java'
end
